config/routes.rb
Rails.application.routes.draw do

  get "/", to: "welcome#index", as: "root"

  get "/register", to: "users#new", as: "registration"

  get '/oauth', to: redirect('/auth/ynab'), as: 'oauth'

  get 'login', to: "sessions#new", as: 'login'
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: "users#show", as: "dashboard"

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')


  get "/privacy", to: "privacy#show", as: "privacy"

  resources :users, only: [:new, :create]

  # namespace :users do
  #   put "/categories", to: "categories#update", as: "category_update"
  # end

  put "/categories", to: "categories#update", as: "categories"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
# class Budget < ApplicationRecord
# 	belongs_to :user
# 	has_many :categories

# 	validates_presence_of :user_id
# 	validates_presence_of :ynab_bid
# 	validates_presence_of :name

# end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :user
	has_many :notifications

	validates_presence_of :ynab_cid
	validates_presence_of :name
	validates_presence_of :budget_id
end

app/models/day.rb
class Day < ApplicationRecord
	belongs_to :notification

	validates_presence_of :notification_id
	validates_presence_of :day

end

app/models/get_ynab_user_data.rb
class GetYnabUserData

  def initialize(token)
    @token = token
	end
	
	def self.get_it(user)
		token = user.tokens.last.token		
    new(token).get_it(user)
	end
	
  def get_it(user)
    yuid = YnabService.new(@token).get_uid
    user.tokens.last.update(uid: yuid)
    user.tokens.last.save
  end

  def self.check_it(token)
    new(token).check_it(token)
  end

  def check_it(token)
    YnabService.new(@token).get_uid
  end
  
	
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :category
	has_many :days

	validates_presence_of :category_id
	validates_presence_of :time

end

app/models/snapshot.rb
class Snapshot

	attr_reader :name,
							:budgeted,
							:spent,
							:remaining

	def initialize(data)
		@name = data[:name]
		@budgeted = data[:budgeted].to_f / 1000
		@spent = data[:activity].to_f / 1000
		@remaining = data[:balance].to_f / 1000
	end

	def daily_allotment
		today = Date.today.day
		end_of_month = Date.today.end_of_month.day
		(@remaining / (end_of_month - today)).round(2)
	end

end

app/models/token.rb
class Token < ApplicationRecord
	belongs_to :user

	validates_presence_of :token
	validates_presence_of :user_id
	validates_presence_of :refresh_token

end

app/models/user.rb
class User < ApplicationRecord
	has_many :tokens
	has_many :categories

	validates_presence_of :name
	validates_presence_of :phone
	validates_presence_of :email
	validates_uniqueness_of :email

	def tracked_category
		self.categories.find_by(tracked: true)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def update
		to_update = current_user.categories.find_by(ynab_cid: params["category"])
		current_user.categories.update_all(tracked: false)
		to_update.update(tracked: true)
		redirect_to dashboard_path
	end

end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController

	def show
		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user ||= User.new
	end

	def create
		data = request.env["omniauth.auth"]["credentials"]
		token_code = data["token"]
		if current_user
			@user = current_user
			token_entry = @user.tokens.new(token: token_code, refresh_token: data["refresh_token"])
			if token_entry.save
				uid = GetYnabUserData.get_it(@user)
				flash[:success] = "Successully Logged in through YNAB!"
				redirect_to dashboard_path
			else
				flash[:failure] = "Something went wrong."
				redirect_to root_path
			end
		else
			user_id = GetYnabUserData.check_it(token_code)
			user = Token.find_by(uid: user_id).user
			user.tokens.last.update(token: token_code, refresh_token: data["refresh_token"]) if user.tokens.last.token != token_entry
			session[:user_id] = user.id
			redirect_to dashboard_path
		end
	end

	def destroy
		session[:user_id] = nil
    redirect_to root_path
  end



private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(ready_params)
		if @user.save
			session[:user_id] = @user.id
			UserTexter.welcome(@user).deliver
			UserWelcomerMailer.welcome(@user).deliver_now
			redirect_to oauth_path
		else
			flash[:error] = 'Email already in use.'
			redirect_to registration_path
    end
	end

	def show
		@facade = DashboardFacade.new(current_user)
	end

	private

	def ready_params
		new_params = user_params
		raw_phone = new_params["phone"]
		new_phone = raw_phone.scan(/\d+/).join
		new_phone[0] == "1" ? new_phone[0] = "" : new_phone
		new_params["phone"] = new_phone unless new_phone.length != 10
		return new_params
	end

	def user_params
   params.require(:user).permit(:email, :name, :phone)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budg-It</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
  </head>

  <body>
    <header>
      <div class="container">
        <a class="logo" href="/">
          <h1>Budg-It</h1>
        </a>
        <nav>
          <% if current_user %>
            <%= link_to "Log Out", logout_path, method: 'delete' %>
          <% else %>
            <%=link_to "Register", registration_path %>
            <%=link_to "Log In", login_path %>
          <% end %>
        </nav>
      </div>
    </header>
    <div class="content">
      <div class="flash-msgs">
       <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: name %>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        <div class="footer-text">
          <p>Backend Module 3 Turing School of Software Project</p>
          <p>By: Silvestre Cuellar, Dan Hutchinson, and Timothy Fell</p>
          <p><%= link_to 'Privacy Policy', privacy_path %></p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/privacy/show.html.erb
<h1>Privacy Policy</h1>

<p>Budg-It does not consume or collect private financial or account data. Budg-It takes all reasonable measures to ensure that API data from YNAB API is secure and protected. No private or confidential user financial data is stored on Budg-It's servers.</p>

app/views/user_texter/welcome.text.erb
Welcome to Budg-It <%= @user.name %>!
You are on your way to reaching your economic goals.

**If you haven't already, please visit Budg-It and select the category you wish to track.**

Budg-It allows you to view on-demand, at-a-glance snapshot summaries for any of the budget categories within the first, "Immediate-Obligations", category group of your default budget from You Need a Budget.

Stay tuned for coming iterations: In the future, Budg-It will offer you the ability to schedule budget snapshots, to be sent to your email, or even here on your phone!

Thanks for using Budg-It!
Sincerely,
the Budg-It team

app/views/users/new.html.erb
<section>
	<div class="container">
		<h1>Register</h1>
		<%= form_for @user do |f| %>
			<%= f.label :name%>
			<%= f.text_field :name, placeholder: "Your Name" %><br>
			<%= f.label :phone%>
			<%= f.text_field :phone, placeholder: "###-###-####" %><br>
			<%= f.label :email %>
			<%= f.text_field :email, placeholder: "Your Email Address" %><br>
			<%= f.submit "Register User"%>
			<p class="privacy_policy"><%= link_to "Privacy Policy", privacy_path %></p>
		<% end %>
	</div>
</section>

app/views/users/show.html.erb
<section>
	<div class="container">
		<h2><%= @facade.username %>'s Dashboard</h2>

		<% if @facade.tracked_category == nil %>
			<%@facade.create_categories%>
			<div>
				<p>Please Select Category to Track:</p>
			</div>
			<%= form_tag(categories_path, method: "put") do %>
				<% @facade.all_categories.each do |cat| %>
					<%= radio_button_tag :category, cat.ynab_cid, class: "category" %> <%= cat.name %> <br>
				<% end %>
					<%= submit_tag("Select Category") %>
			<% end %>

		<% else %>
			<div class="category-data">
				<h3>Monthly <%= @facade.snapshot.name %> Snapshot</h3>
				<div class="api-data">
					<ul>
						<li>Budgeted: <%= number_to_currency(@facade.snapshot.budgeted) %></li>
						<li>Activity: <%= number_to_currency(@facade.snapshot.spent) %></li>
						<li>Remaining Balance: <%= number_to_currency(@facade.snapshot.remaining) %></li>
						<li>Daily Allotment: <%= number_to_currency(@facade.snapshot.daily_allotment) %> per day</li>
					</ul>
					<div id="budget_pie"></div>
					<script>
			      window.onload = function() {

			      var chart = new CanvasJS.Chart("budget_pie", {
			      	animationEnabled: true,
			      	data: [{
			      		type: "pie",
			      		startAngle: 240,
			      		yValueFormatString: "##0.00\"%\"",
			      		indexLabel: "{label} {y}",
			      		dataPoints: [
			      			{y: <%= (@facade.snapshot.spent / @facade.snapshot.budgeted) * 100 %>, label: "Activity"},
			      			{y: <%= (@facade.snapshot.remaining / @facade.snapshot.budgeted) * 100 %>, label: "Remaining"},
			      		]
			      	}]
			      });
			      chart.render();
			      }
			    </script>
				</div>
			</div>
		<% end %>
	</div>
</section>

app/views/welcome/index.html.erb
<section class="landing white">
  <div class="blur-bg">
    </div>
  <div class="container">
    <div class="welcome">
      <h2>Welcome to Budg-It!</h2>
      <% if current_user %>
        <%= link_to 'My Dashboard', dashboard_path, class: 'cta-button' %>
      <% else %>
        <%= link_to 'Register Now', registration_path, class: 'cta-button' %>
      <% end %>
    </div>
  </div>
</section>
<section class="features white">
  <div class="container">
    <h3>About Budg-It</h3>
    <p>Budg-It is an app that provides at-a-glance budget snapshots for a user's You Need a Budget profile. It uses YNAB API data and OmniAuth-YNAB. Budg-It does not consume or store any confidential user financial data.</p>
  </div>
</section>